version: "3"
services:
  mariadb:
    image: mariadb
    container_name: mariadba1
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE: PEPSA
    volumes:
      - mariadb_dataa1:/var/lib/mysql
      - ./Biblioteca.sql:/docker-entrypoint-initdb.d/Biblioteca.sql:ro
    user: mysql
    networks:
      - backend
    secrets:
      - db_root_password

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmina1
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    ports:
      - 7001:80
    links:
      - mariadb
    depends_on:
      - mariadb
    networks:
      - backend

  python:
    build: .
    container_name: pythona1
    env_file: .env  
    environment:
      PYTHONUNBUFFERED: 1
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: PEPSA
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
      SECRET_KEY: ${SECRET_KEY}
      WTF_CSRF_SECRET_KEY: ${WTF_CSRF_SECRET_KEY}
      DEBUG: 'False'
    depends_on:
      - mariadb
    networks:
      - backend
    volumes:
      - ./logAPI/:/app/logs

  apache:
    build: ./apache
    container_name: apachea1
    ports:
      - 6011:443
      - 6001:80
    depends_on:
      - python
    links:
      - python
    volumes:
      - ./apache/static:/var/www/html
      - ./logwaf:/var/log/apache2
    networks:
      - backend

secrets:
  db_root_user:
    file: ./secretos/db_root_user.txt
  db_root_password:
    file: ./secretos/db_root_password.txt
  db_user_username:
    file: ./secretos/db_user_username.txt
  db_user_password:
    file: ./secretos/db_user_password.txt

networks:
  backend:
    driver: bridge

volumes:
  mariadb_dataa1: