version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave #No funciona nada más que con el usuario root
      MARIADB_DATABASE: PEPS
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./Biblioteca.sql:/docker-entrypoint-initdb.d/Biblioteca.sql
    user: mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb

  python:
    build: .
    container_name: python
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - 9094:8080
    depends_on:
      - mariadb

  apache:
    build: ./apache
    container_name: apache
    ports:
      - 9095:80

    # meter el html, en volumen o en el build. Mejor en volumen ya que en el build habria que rebuildearlo por cada cambio que se hiciera.
    # a lo mejor en un futuro, cuando haya que versionarlo, nos conviene más meterlo en la build

    #volumes:
    #  - ./web:/var/www/html

    
    