version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: PEPSA
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./Biblioteca.sql:/docker-entrypoint-initdb.d/Biblioteca.sql
    user: mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb

  python:
    build: .
    container_name: python
    environment:
      PYTHONUNBUFFERED: 1
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPSA
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - 9094:8080
    depends_on:
      - mariadb

  apache:
    build: ./apache
    container_name: apache
    ports:
      - 9095:80
    volumes:
      - ./apache/static:/var/www/html

    # meter el html, en volumen o en el build. Mejor en volumen ya que en el build habria que rebuildearlo por cada cambio que se hiciera.
    # a lo mejor en un futuro, cuando haya que versionarlo, nos conviene más meterlo en la build


    
    